/* Algerian wilayas + a selection of communes per wilaya. Not
   exhaustive — for production, plug into a real geo dataset. The
   smaller wilayas only carry their capital here. */

export type Wilaya = {
  code: string;
  name: string;
  communes: string[];
};

export const WILAYAS: Wilaya[] = [
  { code: "01", name: "Adrar", communes: ["Adrar", "Reggane", "Aoulef", "Timimoun"] },
  { code: "02", name: "Chlef", communes: ["Chlef", "Ténès", "Boukadir", "El Marsa", "Oued Fodda"] },
  { code: "03", name: "Laghouat", communes: ["Laghouat", "Aflou", "Ksar El Hirane"] },
  { code: "04", name: "Oum El Bouaghi", communes: ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'Lila"] },
  { code: "05", name: "Batna", communes: ["Batna", "Barika", "Arris", "Merouana", "N'Gaous", "Tazoult"] },
  { code: "06", name: "Béjaïa", communes: ["Béjaïa", "Akbou", "Sidi Aïch", "El Kseur", "Aokas", "Tichy"] },
  { code: "07", name: "Biskra", communes: ["Biskra", "Tolga", "Sidi Okba", "Ouled Djellal"] },
  { code: "08", name: "Béchar", communes: ["Béchar", "Beni Abbès", "Kenadsa"] },
  { code: "09", name: "Blida", communes: ["Blida", "Boufarik", "Mouzaïa", "El Affroun", "Bouinan", "Soumaa"] },
  { code: "10", name: "Bouira", communes: ["Bouira", "Lakhdaria", "M'Chedallah", "Sour El Ghozlane", "Aïn Bessem"] },
  { code: "11", name: "Tamanrasset", communes: ["Tamanrasset", "In Salah", "In Guezzam"] },
  { code: "12", name: "Tébessa", communes: ["Tébessa", "Bir El Ater", "Cheria", "El Aouinet"] },
  { code: "13", name: "Tlemcen", communes: ["Tlemcen", "Maghnia", "Ghazaouet", "Nedroma", "Remchi"] },
  { code: "14", name: "Tiaret", communes: ["Tiaret", "Sougueur", "Frenda", "Mahdia"] },
  { code: "15", name: "Tizi Ouzou", communes: ["Tizi Ouzou", "Azazga", "Draâ Ben Khedda", "Boghni", "Larbaâ Nath Irathen", "Tigzirt"] },
  {
    code: "16",
    name: "Alger",
    communes: [
      "Alger Centre",
      "Bab El Oued",
      "Bab Ezzouar",
      "Hydra",
      "Kouba",
      "Bir Mourad Raïs",
      "El Harrach",
      "Hussein Dey",
      "Birkhadem",
      "Dar El Beïda",
      "Cheraga",
      "Draria",
    ],
  },
  { code: "17", name: "Djelfa", communes: ["Djelfa", "Aïn Oussera", "Hassi Bahbah", "Messaad"] },
  { code: "18", name: "Jijel", communes: ["Jijel", "El Milia", "Taher", "Chekfa"] },
  {
    code: "19",
    name: "Sétif",
    communes: [
      "Sétif",
      "El Eulma",
      "Aïn Oulmène",
      "Bougaa",
      "Aïn El Kebira",
      "Aïn Azel",
      "Aïn Arnat",
      "Bir El Arch",
    ],
  },
  { code: "20", name: "Saïda", communes: ["Saïda", "Aïn El Hadjar", "Ouled Brahim"] },
  { code: "21", name: "Skikda", communes: ["Skikda", "Azzaba", "Collo", "El Harrouch", "Tamalous"] },
  { code: "22", name: "Sidi Bel Abbès", communes: ["Sidi Bel Abbès", "Telagh", "Sfisef", "Ben Badis"] },
  { code: "23", name: "Annaba", communes: ["Annaba", "El Bouni", "Berrahal", "Sidi Amar", "El Hadjar"] },
  { code: "24", name: "Guelma", communes: ["Guelma", "Bouchegouf", "Héliopolis", "Oued Zenati"] },
  {
    code: "25",
    name: "Constantine",
    communes: ["Constantine", "El Khroub", "Hamma Bouziane", "Aïn Smara", "Didouche Mourad"],
  },
  { code: "26", name: "Médéa", communes: ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Ouzera"] },
  { code: "27", name: "Mostaganem", communes: ["Mostaganem", "Aïn Tédelès", "Hassi Mameche", "Sidi Lakhdar"] },
  { code: "28", name: "M'Sila", communes: ["M'Sila", "Bou Saâda", "Aïn El Melh", "Magra", "Sidi Aïssa"] },
  { code: "29", name: "Mascara", communes: ["Mascara", "Sig", "Tighennif", "Mohammadia"] },
  { code: "30", name: "Ouargla", communes: ["Ouargla", "Touggourt", "Hassi Messaoud", "Rouissat"] },
  {
    code: "31",
    name: "Oran",
    communes: [
      "Oran",
      "Bir El Djir",
      "Es Sénia",
      "Aïn El Türk",
      "Arzew",
      "Bethioua",
      "Gdyel",
      "Sidi Chami",
    ],
  },
  { code: "32", name: "El Bayadh", communes: ["El Bayadh", "Rogassa", "Boualem"] },
  { code: "33", name: "Illizi", communes: ["Illizi", "Djanet", "In Aménas"] },
  { code: "34", name: "Bordj Bou Arréridj", communes: ["Bordj Bou Arréridj", "Ras El Oued", "Mansoura", "El Achir"] },
  { code: "35", name: "Boumerdès", communes: ["Boumerdès", "Boudouaou", "Khemis El Khechna", "Bordj Menaïel", "Dellys"] },
  { code: "36", name: "El Tarf", communes: ["El Tarf", "El Kala", "Drean", "Bouhadjar"] },
  { code: "37", name: "Tindouf", communes: ["Tindouf"] },
  { code: "38", name: "Tissemsilt", communes: ["Tissemsilt", "Theniet El Had", "Bordj Bou Naâma"] },
  { code: "39", name: "El Oued", communes: ["El Oued", "Robbah", "Guemar", "Reguiba"] },
  { code: "40", name: "Khenchela", communes: ["Khenchela", "Kaïs", "Babar"] },
  { code: "41", name: "Souk Ahras", communes: ["Souk Ahras", "Sedrata", "Mechroha"] },
  { code: "42", name: "Tipaza", communes: ["Tipaza", "Koléa", "Hadjout", "Cherchell", "Sidi Amar", "Bou Ismaïl"] },
  { code: "43", name: "Mila", communes: ["Mila", "Chelghoum Laïd", "Ferdjioua", "Grarem Gouga"] },
  { code: "44", name: "Aïn Defla", communes: ["Aïn Defla", "Khemis Miliana", "Miliana", "Boumedfaa"] },
  { code: "45", name: "Naâma", communes: ["Naâma", "Mécheria", "Aïn Sefra"] },
  { code: "46", name: "Aïn Témouchent", communes: ["Aïn Témouchent", "Hammam Bou Hadjar", "Beni Saf"] },
  { code: "47", name: "Ghardaïa", communes: ["Ghardaïa", "Berriane", "Metlili", "El Atteuf"] },
  { code: "48", name: "Relizane", communes: ["Relizane", "Yellel", "Oued Rhiou", "Mazouna"] },
  { code: "49", name: "Timimoun", communes: ["Timimoun", "Ouled Saïd"] },
  { code: "50", name: "Bordj Badji Mokhtar", communes: ["Bordj Badji Mokhtar"] },
  { code: "51", name: "Ouled Djellal", communes: ["Ouled Djellal", "Sidi Khaled"] },
  { code: "52", name: "Béni Abbès", communes: ["Béni Abbès", "Tabelbala"] },
  { code: "53", name: "In Salah", communes: ["In Salah", "Foggaret Ezzaouia"] },
  { code: "54", name: "In Guezzam", communes: ["In Guezzam"] },
  { code: "55", name: "Touggourt", communes: ["Touggourt", "Megarine", "Témacine"] },
  { code: "56", name: "Djanet", communes: ["Djanet", "Bordj El Haouasse"] },
  { code: "57", name: "El M'Ghair", communes: ["El M'Ghair", "Djamaa", "Sidi Khellil"] },
  { code: "58", name: "El Meniaa", communes: ["El Meniaa", "Hassi Gara"] },
];
